stages:
  - validate
  - build
  - deploy

builderrors:
  stage: validate
  allow_failure: true
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/gramener/builderrors:3.0.2
  script: builderrors

sast:
  stage: validate
  allow_failure: true
  image: registry.gitlab.com/gitlab-org/security-products/sast:latest
  script:
    - gl-sast

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY    
  script:
    - DOCKER_BUILDKIT=0 docker build -t $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H) .
    - docker push $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H)
    - docker tag $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H) $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

  only:
    - master


deploy:
  stage: deploy   
  script:
    - chmod 400 -v ${DEV_SERVER_KEY} 
    - echo ${DEV_SERVER_KEY}
    - scp -o StrictHostKeyChecking=no -i ${DEV_SERVER_KEY} deploy.sh docker-compose.yml ubuntu@${DEV_SERVER_IP}://home/ubuntu/repos/apex-frontend
    - ssh -o stricthostkeychecking=no -i ${DEV_SERVER_KEY} ubuntu@${DEV_SERVER_IP} "sudo su - ubuntu; cd repos/apex-frontend; sh deploy.sh"

  only:
    - master
