stages:
  - validate
  - build
  - build-d2c
  - deploy
  - deploy-d2c
  - production

builderrors:
  stage: validate
  allow_failure: true
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/gramener/builderrors:3.0.2
  script: builderrors

sast:
  stage: validate
  allow_failure: true
  image: registry.gitlab.com/gitlab-org/security-products/sast:latest
  script:
    - gl-sast

build:
  stage: build
  image: docker:latest
  variables:
    server: "development" 
  services:
    - name: docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - DOCKER_BUILDKIT=0 docker build --build-arg server=$server -t $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H) .
    - docker push $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H)
    - docker tag $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H) $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

  only:
    - master

build-d2c:
  stage: build-d2c
  image: docker:latest
  variables:
    server: "development" 
  services:
    - name: docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - DOCKER_BUILDKIT=0 docker build --build-arg server=$server -t $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H) .
    - docker push $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H)
    - docker tag $CI_REGISTRY_IMAGE:$(date +%Y.%m.%d.%H) $CI_REGISTRY_IMAGE:latest-d2c
    - docker push $CI_REGISTRY_IMAGE:latest-d2c

  only:
    - renewaljourney

deploy:
  stage: deploy
  script:
    - chmod 400 -v ${DEV_SERVER_KEY}
    - echo ${DEV_SERVER_KEY}
    - scp -o StrictHostKeyChecking=no -i ${DEV_SERVER_KEY} deploy.sh docker-compose.yml ubuntu@${DEV_SERVER_IP}://home/ubuntu/repos/apex-frontend
    - ssh -o stricthostkeychecking=no -i ${DEV_SERVER_KEY} ubuntu@${DEV_SERVER_IP} "sudo su - ubuntu; cd repos/swarm/apex-frontend; sh deploy.sh"

  only:
    - master

deploy-d2c:
  stage: deploy-d2c
  script:
    - chmod 400 -v ${DEV_SERVER_KEY}
    - echo ${DEV_SERVER_KEY}
    - scp -o StrictHostKeyChecking=no -i ${DEV_SERVER_KEY} deploy.sh docker-compose.yml ubuntu@${DEV_SERVER_IP}://home/ubuntu/repos/apex-frontend
    - ssh -o stricthostkeychecking=no -i ${DEV_SERVER_KEY} ubuntu@${DEV_SERVER_IP} "sudo su - ubuntu; cd repos/swarm/apex-fe-d2c; sh deploy.sh"
  only:
    - renewaljourney
production:
  stage: production
  variables:
    server: "production" 
  services:
    - name: docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - DOCKER_BUILDKIT=0 docker build --build-arg server=$server -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $CI_REGISTRY_IMAGE:latest-production
    - docker push $CI_REGISTRY_IMAGE:latest-production
    - chmod 400 -v ${PROD_SERVER_KEY}
    - ssh -o stricthostkeychecking=no -i ${PROD_SERVER_KEY} ubuntu@${PROD_SERVER_IP} "sudo su - ubuntu; docker login -u clone_token -p "${DOCKER_PASSWORD}" registry.gitlab.renewbuy.in; cd repos/apex-frontend; sh deploy.sh"
    - ssh -o stricthostkeychecking=no -i ${PROD_SERVER_KEY} ubuntu@${PROD_SERVER_IP} "sudo su - ubuntu; docker login -u clone_token -p "${DOCKER_PASSWORD}" registry.gitlab.renewbuy.in; cd repos/d2c_fe; sh deploy.sh"
    - ssh -o stricthostkeychecking=no -i ${PROD_SERVER_KEY} ubuntu@${PROD_SERVER_IP_1} "sudo su - ubuntu; docker login -u clone_token -p "${DOCKER_PASSWORD}" registry.gitlab.renewbuy.in; cd repos/apex-frontend; sh deploy.sh"
  only:
    - tags
