version: '3'
services:
  web:
    image: registry.gitlab.renewbuy.in/apex/apex_frontend:latest
    container_name: apex-frontend
    volumes:
      #- env settings
      - logs-volume:/var/log/apex-frontend
        #- ./config/nginx:/etc/nginx/conf.d
    expose:
      - 9001
    ports:
      - "9001:9001"    
    networks:
      - dev-apex-network
volumes:
  logs-volume:
  static-root:
networks:
   dev-apex-network:
     external: true