version: '3'
services:
  nginx:
      image: nginx:latest
      ports:
        - 8000:8000
      volumes:
        - ./config/nginx:/etc/nginx/conf.d
      depends_on:
        - web
      networks:
        - dev-apex-network
  web:
    #build: .
    image: registry.gitlab.renewbuy.in/apex/apex_frontend:latest
    container_name: apex-frontend
    volumes:
      #- env settings
      - logs-volume:/var/log/apex-frontend
        #- ./config/nginx:/etc/nginx/conf.d
    expose:
      - 9001
    networks:
      - dev-apex-network
volumes:
  logs-volume:
  static-root:
networks:
   dev-apex-network:
      name: dev-apex-network