# To execute this docker-compose yml file use `docker-compose -f docker-compose-v2.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v2.yml down`
version: '2'
services:
  apex_ui_automation:
    image: apex_ui_automation:latest
    command: bash run.sh
    depends_on:
      - chrome-apex
  
  chrome-apex:
    image: selenium/node-chrome:4.5.3-20221024
    shm_size: 2gb
    depends_on:
      - selenium-hub-apex
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub-health
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=2

      
  selenium-hub-apex:
    image: selenium/hub:4.5.3-20221024
#    ports:
#      - "4442:4442"
#      - "4443:4443"
#      - "4444:4444"

