    # partner journey
    sign_with_password= //*[contains(text(),' Sign In with Password ')]
    enter_email_partner= //*[@id='form_email']
    etner_password_partner= //*[@id='form_password']
    sign_in= //*[@type='submit']
    wait_for_login_success= //*[@id='userProfile']

    #  product page x- path
    two_wheel= (//*[contains(text(),'Two Wheeler')])[1]
    four_wheel= (//*[contains(text(),'Private Car')])[1]
    commercial_wheel= (//*[contains(text(),'Commercial Vehicle')])[1]
    registration_number= //input
    get_vehicle_details_with_reg_num= //*[@id-automation='getVehicleDetailsId']
    proceed_without_vehicle_number= //*[contains(text(),' Proceed without Vehicle Number ')]


    #  mmv details page
    search_vehicle=//*[@id-automation='searchVehicle']
    select_vehicle=//span[@class="mat-option-text"]//span
    search_rto= //*[@id-automation='rtoData']
    select_drop_down_option=//*[@class='mat-option-text']
    enter_reg_year=//*[@id-automation="registrationYearId"]
    search_previous_insurer=//*[@id-automation="previousInsuranceId"]
    enter_policy_expiry=//*[@id-automation="policy_expiry_date"]
    get_vehicle_details=//*[@id-automation="getVehicleDetailsId"]

    #mmv confirmation page
    above_details_correct_btn=//*[contains(text(),'Above details are correct')]
    